# Generated by Django 2.1.4 on 2019-05-01 06:08

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0002_email_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthenticatedReplay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_hash', models.CharField(max_length=200)),
                ('user_in_game_name', models.CharField(max_length=50)),
                ('opponent_in_game_name', models.CharField(max_length=50)),
                ('played_at', models.DateTimeField()),
                ('game_map', models.CharField(max_length=100)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('region_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='BattlenetAccount',
            fields=[
                ('id', models.CharField(max_length=100, unique=True)),
                ('battletag', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('region_profiles', django.contrib.postgres.fields.jsonb.JSONField()),
                ('user_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.EmailAddress', to_field='email')),
            ],
        ),
        migrations.CreateModel(
            name='UnauthenticatedReplay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_hash', models.CharField(max_length=200)),
                ('player1_profile_id', models.CharField(max_length=20)),
                ('player2_profile_id', models.CharField(max_length=20)),
                ('played_at', models.DateTimeField()),
                ('game_map', models.CharField(max_length=100)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('region_id', models.IntegerField()),
                ('user_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.EmailAddress', to_field='email')),
            ],
        ),
        migrations.AddField(
            model_name='authenticatedreplay',
            name='battlenet_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_profile.BattlenetAccount'),
        ),
    ]
