# Generated by Django 2.1.4 on 2019-02-06 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='battlenetaccount',
            old_name='id',
            new_name='account_id',
        ),
    ]
