# Generated by Django 2.1.4 on 2019-02-09 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='battlenetaccount',
            name='id',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
