# Generated by Django 2.1.4 on 2019-05-02 09:50

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='authenticatedreplay',
            old_name='game_map',
            new_name='map',
        ),
        migrations.RenameField(
            model_name='unauthenticatedreplay',
            old_name='game_map',
            new_name='map',
        ),
        migrations.AddField(
            model_name='authenticatedreplay',
            name='match_summary',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='unauthenticatedreplay',
            name='match_summary',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=1),
            preserve_default=False,
        ),
    ]
