# Generated by Django 2.1.4 on 2019-04-26 12:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReplayInfo',
            fields=[
                ('file_hash', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('user_in_game_name', models.CharField(max_length=50)),
                ('opponent_in_game_name', models.CharField(max_length=50)),
                ('played_at', models.DateTimeField()),
                ('game_map', models.CharField(max_length=100)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('battlenet_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_profile.BattlenetAccount')),
            ],
        ),
    ]
