# Generated by Django 2.1.4 on 2019-02-06 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0002_auto_20190207_0023'),
    ]

    operations = [
        migrations.RenameField(
            model_name='battlenetaccount',
            old_name='account_id',
            new_name='id',
        ),
    ]
