# Generated by Django 2.1.4 on 2019-04-26 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0002_replayinfo'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ReplayInfo',
            new_name='AuthenticatedReplay',
        ),
    ]
