# Generated by Django 2.1.4 on 2019-04-26 21:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_email_max_length'),
        ('user_profile', '0003_auto_20190427_0031'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnauthenticatedReplay',
            fields=[
                ('file_hash', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('player1_in_game_name', models.CharField(max_length=50)),
                ('player2_in_game_name', models.CharField(max_length=50)),
                ('played_at', models.DateTimeField()),
                ('game_map', models.CharField(max_length=100)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('user_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.EmailAddress', to_field='email')),
            ],
        ),
    ]
