# Generated by Django 2.1.4 on 2019-05-06 03:22

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0003_authenticatedreplay_opponent_profile_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='authenticatedreplay',
            name='timeline',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='unauthenticatedreplay',
            name='timeline',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=1),
            preserve_default=False,
        ),
    ]
