# Generated by Django 2.1.4 on 2019-04-27 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0004_unauthenticatedreplay'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='unauthenticatedreplay',
            name='player1_in_game_name',
        ),
        migrations.RemoveField(
            model_name='unauthenticatedreplay',
            name='player2_in_game_name',
        ),
        migrations.AddField(
            model_name='unauthenticatedreplay',
            name='player1_battletag',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='unauthenticatedreplay',
            name='player2_battletag',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
