# Generated by Django 2.2.4 on 2019-08-08 08:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0004_auto_20190506_1522'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='authenticatedreplay',
            name='timeline',
        ),
        migrations.RemoveField(
            model_name='unauthenticatedreplay',
            name='timeline',
        ),
    ]
