# Generated by Django 2.2.4 on 2019-08-09 01:07

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_email_max_length'),
        ('user_profile', '0005_auto_20190808_2004'),
    ]

    operations = [
        migrations.CreateModel(
            name='Replay',
            fields=[
                ('file_hash', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('match_summary', django.contrib.postgres.fields.jsonb.JSONField()),
                ('played_at', models.DateTimeField()),
                ('map', models.CharField(max_length=100)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('region_id', models.IntegerField()),
                ('battlenet_account', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user_profile.BattlenetAccount')),
                ('user_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.EmailAddress', to_field='email')),
            ],
        ),
        migrations.RemoveField(
            model_name='unauthenticatedreplay',
            name='user_account',
        ),
        migrations.DeleteModel(
            name='AuthenticatedReplay',
        ),
        migrations.DeleteModel(
            name='UnauthenticatedReplay',
        ),
    ]
