# Generated by Django 2.1.4 on 2019-04-27 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0005_auto_20190427_1330'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='unauthenticatedreplay',
            name='player1_battletag',
        ),
        migrations.RemoveField(
            model_name='unauthenticatedreplay',
            name='player2_battletag',
        ),
        migrations.AddField(
            model_name='unauthenticatedreplay',
            name='player1_battlenet_id',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='unauthenticatedreplay',
            name='player2_battlenet_id',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
