# Generated by Django 2.2.4 on 2019-08-17 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0006_auto_20190809_1307'),
    ]

    operations = [
        migrations.AddField(
            model_name='replay',
            name='win',
            field=models.BooleanField(null=True),
        ),
    ]
