# Generated by Django 2.2.4 on 2019-08-17 08:29

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0007_replay_win'),
    ]

    operations = [
        migrations.AddField(
            model_name='replay',
            name='players',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={'key': 'value'}),
            preserve_default=False,
        ),
    ]
