# Generated by Django 2.1.4 on 2019-05-01 03:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0007_auto_20190501_1356'),
    ]

    operations = [
        migrations.RenameField(
            model_name='battlenetaccount',
            old_name='profiles',
            new_name='region_profiles',
        ),
    ]
