# Generated by Django 2.1.4 on 2019-05-01 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0008_auto_20190501_1517'),
    ]

    operations = [
        migrations.AddField(
            model_name='authenticatedreplay',
            name='region',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='unauthenticatedreplay',
            name='region',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
