# Generated by Django 2.2.4 on 2019-08-17 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0008_replay_players'),
    ]

    operations = [
        migrations.RenameField(
            model_name='replay',
            old_name='match_summary',
            new_name='match_data',
        ),
        migrations.AddField(
            model_name='replay',
            name='match_length',
            field=models.IntegerField(default=100),
            preserve_default=False,
        ),
    ]
