# Generated by Django 2.1.4 on 2019-05-01 05:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0009_auto_20190501_1702'),
    ]

    operations = [
        migrations.RenameField(
            model_name='authenticatedreplay',
            old_name='region',
            new_name='region_id',
        ),
        migrations.RenameField(
            model_name='unauthenticatedreplay',
            old_name='region',
            new_name='region_id',
        ),
    ]
