# Generated by Django 2.2.4 on 2019-09-19 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0010_replay_user_match_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='replay',
            name='user_match_id',
            field=models.IntegerField(null=True),
        ),
    ]
