# Generated by Django 2.2.4 on 2020-02-16 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0011_auto_20190919_1817'),
    ]

    operations = [
        migrations.AlterField(
            model_name='replay',
            name='file_hash',
            field=models.CharField(max_length=64),
        ),
        migrations.AddField(
            model_name='replay',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name='replay',
            constraint=models.UniqueConstraint(fields=('file_hash', 'user_account'), name='unique_replay'),
        ),
    ]
