# Generated by Django 2.2.4 on 2020-03-13 20:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_email_max_length'),
        ('user_profile', '0012_auto_20200216_1603'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeatureVote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vote_id', models.UUIDField(editable=False)),
                ('feature', models.CharField(max_length=100)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('user_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.EmailAddress', to_field='email')),
            ],
        ),
    ]
