# Generated by Django 2.2.4 on 2020-03-13 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0013_featurevote'),
    ]

    operations = [
        migrations.AddField(
            model_name='featurevote',
            name='comment',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
