# Generated by Django 2.2.4 on 2020-07-12 06:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0014_featurevote_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='battlenetaccount',
            name='linked_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
