# Generated by Django 2.2.4 on 2020-08-28 05:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_email_max_length'),
        ('user_profile', '0015_battlenetaccount_linked_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback', models.CharField(max_length=300)),
                ('feedback_type', models.CharField(choices=[('I', 'Issue'), ('S', 'Suggestion')], max_length=1)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('user_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.EmailAddress', to_field='email')),
            ],
        ),
    ]
