# Generated by Django 2.1.4 on 2018-12-13 11:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('upload_file', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='replay',
            name='file_path',
            field=models.CharField(default='/filepath', max_length=200),
        ),
        migrations.AddField(
            model_name='replay',
            name='upload_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
