# Generated by Django 2.1.4 on 2019-02-08 08:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('upload_file', '0002_replayinfo_battlenet_account'),
    ]

    operations = [
        migrations.RenameField(
            model_name='replayinfo',
            old_name='file_path',
            new_name='bucket_path',
        ),
    ]
