# Generated by Django 2.1.4 on 2018-12-16 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('upload_file', '0002_auto_20181214_0026'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Replay',
        ),
    ]
