# Generated by Django 2.1.4 on 2019-04-26 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('upload_file', '0002_replayinfo_battlenet_account'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='replayinfo',
            name='battlenet_account',
        ),
        migrations.DeleteModel(
            name='ReplayInfo',
        ),
    ]
