# Generated by Django 2.1.4 on 2019-02-08 08:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('upload_file', '0003_auto_20190208_2115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='replayinfo',
            name='battlenet_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_profile.BattlenetAccount', unique=True),
        ),
    ]
