# Generated by Django 2.1.4 on 2019-02-03 06:20

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload_file', '0004_replay'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReplayInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player1', django.contrib.postgres.fields.jsonb.JSONField()),
                ('player2', django.contrib.postgres.fields.jsonb.JSONField()),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
