# Generated by Django 2.1.4 on 2019-02-08 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload_file', '0005_auto_20190208_2129'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='replayinfo',
            name='bucket_path',
        ),
        migrations.RemoveField(
            model_name='replayinfo',
            name='id',
        ),
        migrations.AddField(
            model_name='replayinfo',
            name='file_hash',
            field=models.CharField(default=None, max_length=200, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
