# Generated by Django 2.1.4 on 2019-02-06 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload_file', '0005_replayinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='replay',
            name='file',
            field=models.FileField(upload_to='replays'),
        ),
    ]
