# Generated by Django 2.1.4 on 2019-02-09 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload_file', '0006_auto_20190208_2154'),
    ]

    operations = [
        migrations.RenameField(
            model_name='replayinfo',
            old_name='player2',
            new_name='opponent',
        ),
        migrations.RenameField(
            model_name='replayinfo',
            old_name='player1',
            new_name='user',
        ),
        migrations.AddField(
            model_name='replayinfo',
            name='game_map',
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='replayinfo',
            name='played_at',
            field=models.DateTimeField(default=None),
            preserve_default=False,
        ),
    ]
