# Generated by Django 2.1.4 on 2019-02-06 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload_file', '0006_auto_20190207_0010'),
    ]

    operations = [
        migrations.AddField(
            model_name='replay',
            name='bucket_path',
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='replay',
            name='file',
            field=models.FileField(upload_to=models.CharField(max_length=100)),
        ),
    ]
